version: "3.1"

services:
  
  db:
    image: mysql:latest
    container_name: "e_shop_db"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_e_shop:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_shop
      MYSQL_DATABASE: shop
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"

  web:
    user: ${UID}
    build: .
    tty: true
    container_name: "e_shop_web"
    environment:
      - DJANGO_SETTINGS_MODULE=e_shop.settings
    command: bash -c "./bin/wait-for-it.sh db:3306 & python ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - "./code:/code"
    depends_on:
      - db
