# Generated by Django 2.2.1 on 2019-05-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shipping_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_type', models.CharField(max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_region_id', models.IntegerField()),
            ],
            options={
                'db_table': 'shipping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingRegion',
            fields=[
                ('shipping_region_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shipping_region',
                'managed': False,
            },
        ),
    ]
